package enzocesarano.D3_Esercizio.exceptions;

public class NotFoundException extends RuntimeException {
    public NotFoundException(long id) {
        super("Il record con id " + id + " non Ã¨ stato trovato!");
    }
}
